version: '3'
services:
  dev:
    image: node
    working_dir: /app
    command: npm start
    volumes:
      - ./:/app
    ports:
      - 8000:8000
      - 35729:35729
  speaker:
    image: node
    working_dir: /app
    command: node plugin/notes-server
    volumes:
      - ./:/app
    ports:
      - 1947:1947
